package com.stand.blocks;

public enum Tags {
	
	OVERWOLD, UNDERWORLD, NETHER, END, OCEAN, PLANTS, PLANTABLE, WOOD, ROCK, CAVES, ORES, STANDABLE, LIQUID, ARMOUR, MOB_DROPS, THROWABLE, EATABLE, CRAFTABLE;

}
